#!/bin/bash

# TTS-MacOS v2 - Quick Demo Script
# Demonstrates key features of the dual-engine TTS system

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🎤 TTS-MacOS v2 - Feature Demo${NC}"
echo "================================="

# Check if we're in the right directory
if [ ! -f "mcp_server_v2" ]; then
    echo "❌ Error: Please run this script from the TTS-MacOS v2 directory"
    exit 1
fi

# Activate virtual environment
if [ -f "activate-tts-v2.sh" ]; then
    echo -e "${BLUE}🔌 Activating TTS-MacOS v2 environment...${NC}"
    source activate-tts-v2.sh
else
    echo -e "${YELLOW}⚠️  Virtual environment not found. Please run ./install.sh first${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}🚀 Demo 1: Basic Synthesis with Engine Selection${NC}"
echo "---------------------------------------------------"

echo "🔊 Native Engine (Fast, OS-level):"
./tts-macos-v2 "Hello from the native TTS engine!" --engine native

echo ""
echo "🤖 AI Engine (High quality, multilingual):"
./tts-macos-v2 "Hello from the AI-powered TTS engine!" --engine ai

echo ""
echo "🎯 Auto Selection (Intelligent choice):"
./tts-macos-v2 "Hello from the automatically selected best engine!" --engine auto

echo ""
echo -e "${GREEN}🎭 Demo 2: Voice Discovery${NC}"
echo "-------------------------------"

echo "📋 Available Native Voices:"
./tts-macos-v2 list-voices --engine native --compact

echo ""
echo "🤖 Available AI Voices:"
python3 -c "
try:
    from v2.engines import EngineSelector
    selector = EngineSelector()
    voices = selector.list_all_voices()
    if 'ai' in voices:
        ai_info = voices['ai']
        print(f'  Languages: {len(ai_info.get(\"languages\", []))} supported')
        print(f'  Voice Cloning: {\"✅\" if ai_info.get(\"cloning_support\") else \"❌\"}')
        print(f'  Device: {ai_info.get(\"device\", \"Unknown\")}')
    else:
        print('  AI engine not available')
except Exception as e:
    print(f'  Error: {e}')
"

echo ""
echo -e "${GREEN}🌍 Demo 3: Multi-Language Support${NC}"
echo "------------------------------------"

echo "🇪🇸 Spanish:"
./tts-macos-v2 "Hola mundo, esto es una prueba en español." --language es --engine auto

echo ""
echo "🇫🇷 French:"
./tts-macos-v2 "Bonjour le monde, ceci est un test en français." --language fr --engine auto

echo ""
echo "🇩🇪 German:"
./tts-macos-v2 "Hallo Welt, dies ist ein Test auf Deutsch." --language de --engine auto

echo ""
echo -e "${GREEN}🎵 Demo 4: Quality and Speed Options${NC}"
echo "--------------------------------------"

echo "⚡ Fast Quality (Native engine):"
./tts-macos-v2 "This is fast synthesis using the native engine." --quality fast

echo ""
echo "⚖️  Balanced Quality (Auto selection):"
./tts-macos-v2 "This is balanced quality synthesis." --quality balanced

echo ""
echo "🌟 Premium Quality (AI engine):"
./tts-macos-v2 "This is premium quality synthesis using the AI engine." --quality premium

echo ""
echo -e "${GREEN}💾 Demo 5: Audio File Generation${NC}"
echo "----------------------------------"

# Create demo output directory
mkdir -p demo_output

echo "📁 Saving audio files..."
./tts-macos-v2 "This audio file was generated by the native engine." \
    --output demo_output/native_demo.wav \
    --engine native

./tts-macos-v2 "This audio file was generated by the AI engine." \
    --output demo_output/ai_demo.wav \
    --engine ai

echo "✅ Files saved in demo_output/"
ls -la demo_output/

echo ""
echo -e "${GREEN}🎛️  Demo 6: Configuration Management${NC}"
echo "-------------------------------------"

echo "⚙️  Current configuration:"
./tts-macos-v2 config --show | head -10

echo ""
echo "📊 System information:"
./tts-macos-v2 info | head -10

echo ""
echo -e "${GREEN}🔧 Demo 7: Legacy Compatibility${NC}"
echo "--------------------------------"

echo "🔄 Testing v1.x compatibility mode:"
./tts-macos-v2 legacy "This uses the legacy v1.x system for full compatibility." --voice monica

echo ""
echo -e "${GREEN}🤖 Demo 8: Smart Features (if available)${NC}"
echo "----------------------------------------"

echo "🧠 Testing smart voice recommendation..."
python3 -c "
try:
    from v2.core.smart_features import VoiceRecommender
    recommender = VoiceRecommender()
    result = recommender.recommend_voice(
        text='Welcome to our educational presentation about artificial intelligence',
        language='en',
        voice_type='professional'
    )
    print(f'  Recommended voice: {result[\"voice\"]} (confidence: {result[\"confidence\"]:.2f})')
    print(f'  Reasoning: {result[\"reasoning\"]}')
except Exception as e:
    print(f'  Smart features not available: {e}')
"

echo ""
echo "🌐 Testing automatic language detection..."
python3 -c "
try:
    from v2.core.smart_features import AutoLanguageDetector
    detector = AutoLanguageDetector()
    result = detector.detect_language('Bonjour, comment allez-vous?')
    print(f'  Detected language: {result[\"detected_language\"]}')
    print(f'  Confidence: {result[\"confidence\"]:.2f}')
    print(f'  TTS Language: {result[\"tts_language\"]}')
except Exception as e:
    print(f'  Language detection not available: {e}')
"

echo ""
echo -e "${GREEN}🎯 Demo 9: Voice Cloning (Sample)${NC}"
echo "------------------------------------"

echo "🎭 Voice cloning requires an audio sample file."
echo "To try voice cloning:"
echo "  1. Record 6+ seconds of clear speech as WAV file"
echo "  2. Run: ./tts-macos-v2 clone-voice sample.wav --name 'My Voice'"
echo "  3. Test: ./tts-macos-v2 'Hello from my cloned voice!' --voice 'My Voice'"

echo ""
echo -e "${GREEN}🎉 Demo Complete!${NC}"
echo "=================="

echo ""
echo "📚 What we demonstrated:"
echo "  ✅ Dual-engine architecture (Native + AI)"
echo "  ✅ Intelligent engine selection"
echo "  ✅ Multi-language support"
echo "  ✅ Quality and speed options"
echo "  ✅ Audio file generation"
echo "  ✅ Configuration management"
echo "  ✅ Backward compatibility"
echo "  ✅ Smart features (when available)"
echo ""
echo "🚀 Next steps:"
echo "  1. Try voice cloning with your own audio samples"
echo "  2. Update Claude Desktop to use the v2 MCP server"
echo "  3. Integrate into your projects and workflows"
echo "  4. Explore the documentation for advanced features"
echo ""
echo "📁 Demo files created in: demo_output/"
echo "📖 Documentation: README.md"
echo "🔄 Migration guide: MIGRATION.md"
echo ""
echo -e "${BLUE}Thank you for trying TTS-MacOS v2! 🎤✨${NC}"
